services:
  cvmfs-server:
    build:
      context: .
    
    volumes:
      - .:/workspace
      # Required. Otherwise will get the following error:
      #   Mounting CernVM-FS Storage... (overlayfs) mount: /cvmfs/cvmfs.cluster.watonomous.ca: wrong fs type, bad option, bad superblock on overlay_cvmfs.cluster.watonomous.ca, missing codepage or helper program, or other error.
      # https://cernvm-forum.cern.ch/t/overlayfs-on-top-of-cephfs/120/4
      - /tmp/cvmfs-spool:/var/spool/cvmfs
    
    privileged: true

  # Dummy S3 server for testing. References:
  # - https://github.com/minio/minio/blob/1bc6681176257bdd7a831b053a448412a3589a3c/docs/docker/README.md
  # - https://github.com/minio/minio/issues/4769#issuecomment-331033735
  minio:
    image: minio/minio

    ports:
      - "9000:9000"
      - "9001:9001"

    entrypoint: sh
    command: -c 'mkdir -p /data/cvmfs && /usr/bin/minio server /data --console-address ":9001"'

    environment:
      - MINIO_ROOT_USER=AKIAIOSFODNN7EXAMPLE
      - MINIO_ROOT_PASSWORD=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY